project:
  type: website
  output-dir: docs
  
website:
  title: "Isaac Bain"
  favicon: images/kakapo-logo.png
  twitter-card:
    creator: "@IsaacBain"
  site-url: https://isaacbain.com
  open-graph: true
  google-analytics: "G-0P0B7NPGM0"
  navbar:
    logo: images/kakapo-logo.png
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - blog.qmd
    right:
      - icon: github
        href: https://github.com/isaacbain
      - icon: linkedin
        href: https://www.linkedin.com/in/isaac-bain-4a0227172
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=vtZwgC4AAAAJ&hl=en
      - icon: twitter
        href: https://twitter.com/isaacbain
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

resources:
  - CNAME
  - images/

